baseURL = "http://example.org/"
languageCode = "en-us"
title = "ROBERTCARPENTRY custom woodwork"
theme = "beautifulhugo"


[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "services"
    url = ""
    weight = 2

[[menu.main]]
    parent = "samples"
    name = "Big Image Sample price"
    url = "post/2017-03-07-bigimg-sample"
    weight = 0



[[menu.main]]
   name = "contact"
   url = "contact"
   weight = 3

